services:
  nginx:
    build:
      context: .
    container_name: global-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_EMAIL: ${ACME_EMAIL:-}
      SITES: ${SITES:-portfolio lota animal}
      PORTFOLIO_DOMAIN: ${PORTFOLIO_DOMAIN:-portfolio.bowang.tech}
      PORTFOLIO_ALIASES: ${PORTFOLIO_ALIASES:-}
      PORTFOLIO_UPSTREAM: ${PORTFOLIO_UPSTREAM:-portfolio-app-1:8081}

      LOTA_DOMAIN: ${LOTA_DOMAIN:-lota.bowang.tech}
      LOTA_ALIASES: ${LOTA_ALIASES:-}
      LOTA_UPSTREAM: ${LOTA_UPSTREAM:-lota-web:8080}

      ANIMAL_DOMAIN: ${ANIMAL_DOMAIN:-animal.bowang.tech}
      ANIMAL_ALIASES: ${ANIMAL_ALIASES:-}
      ANIMAL_UPSTREAM: ${ANIMAL_UPSTREAM:-animal-front:18080}
      ANIMAL_API_UPSTREAM: ${ANIMAL_API_UPSTREAM:-animal-server:9090}
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    networks:
      - proxy

volumes:
  certbot_www:
  certbot_certs:

networks:
  proxy:
    name: proxy
